### ISSUE TITLE
Move repositories to the phel-lang organization

### ISSUE THREAD

**Issue by jenshaase** [phel-lang/phel-lang#175]
Move the repositories form my account (jenshaase) to the phel-lang organization. This can be done by repo settings > transfer owner.

**Comment by Chemaclass** [comment]
Repo settings > Transfer owner > "phel-lang", or something like this ;)

**Comment by Chemaclass** [comment]
As part of moving the repos to `phel-lang` organization, I would also update the packagist name from the repos to `phel-lang` as well.

- Instead of `phel/phel` -> `phel-lang/phel`
- The same for the plugin -> `phel/phel-composer-plugin` -> `phel-lang/phel-composer-plugin`

I think the easiest way to do this is:
1. change the names from the `composer.json`
3. push the changes to github
4. remove the repos from packagist
5. submit the repos using the new news 

Better do the plugging first, because it's a dependency from the main repo, and you have to update it using the new name.

**Comment by JesusValera** [comment]
Agree with @Chemaclass, I think is better `phel-lang` than just `phel` :P

**Comment by jenshaase** [comment]
The composer plugin is now moved to the `phel-lang` organization. 
https://github.com/phel-lang/phel-composer-plugin

I published it under the `phel-lang` name to packagist and released version 0.1.0.
https://packagist.org/packages/phel-lang/phel-composer-plugin

**Comment by jenshaase** [comment]
This repository is now moved to the phel-lang organization.

On packagist the package can now be found here: https://packagist.org/packages/phel-lang/phel-lang

The old packages still exist, but I will remove them in the next days.
