### ISSUE TITLE
Set a color for the REPL output depending on the type

### ISSUE THREAD

**Issue by JesusValera** [phel-lang/phel-lang#197]
## 📚  Description

I took this picture from elixir.

![image](https://user-images.githubusercontent.com/6381924/105629639-7940a980-5e44-11eb-9395-92ccd4a04add.png)

I like the idea of colour the output from the REPL console depending on the type.

What do you think? What colours should we use for each element type?

**Comment by jenshaase** [comment]
Yes this can be added to the Printer. However, this should not be enabled by default, since the `print` function in the core library also uses the `Printer`.

First lets define, how many colors we need and then what colors there are. The colors should have high contrast on both white and black backgrounds.

**Comment by jenshaase** [comment]
I would suggest the following colors:

* nil `\033[0;96m%s\033[0m`
* string `\033[0;95m%s\033[0m`
* boolean `\033[0;94m%s\033[0m`
* symbol `\033[0;91m%s\033[0m`
* number `\033[0;92m%s\033[0m`
* Keyword `\033[0;93m%s\033[0m`

Test script
```
<?php

echo sprintf("\033[0;96m%s\033[0m", "nil") . PHP_EOL;
echo sprintf("\033[0;95m%s\033[0m", "\"string\"") . PHP_EOL;
echo sprintf("\033[0;94m%s\033[0m", "true") . PHP_EOL;
echo sprintf("\033[0;91m%s\033[0m", "sym") . PHP_EOL;
echo sprintf("\033[0;92m%s\033[0m", "1234") . PHP_EOL;
echo sprintf("\033[0;93m%s\033[0m", ":keyword") . PHP_EOL;
```
