### ISSUE TITLE
Phel not throwing error when miss typing a word in `ns`

### ISSUE THREAD

**Issue by mabasic** [phel-lang/phel-lang#254]
I had this code:

```
(:require app\config\mail)
  (:requre app\logger))

(logger/debug "something")
```

Notice the `:requre` word. When using `phel run` to run the file it would not complain about `:requre`, but it would say:

```
Phel\Compiler\Emitter\Exceptions\CompiledCodeIsMalformedException: Can not resolve symbol 'logger/debug'
```

If it complained about `:requre` I would not spend half an hour trying to figure out what is wrong. Could this be somehow handled?

**Comment by p810** [comment]
I've only been playing around with the compiler for about a day now, so this is a very naive implementation of this and I'm not sure what side effects it might have (if any), but in the testing I have done [this change](https://github.com/p810/phel-lang/commit/71f9a4892439f10d2966178ae74d81c335c2c0c4) seems to address the issue.

I'm not 100% sure on this due to my limited experience, but it seems like the only valid keywords we might encounter at the top level when analyzing an instance of `NsSymbol` are `:require` and `:use`. Following that assumption I just added an exception if any other keyword was encountered, and suggested the correct spelling if the given keyword was close enough to either one:

```
p810@DESKTOP:~/dev/phel-lang$ ./phel run test.phel
Unexpected keyword encountered in 'ns. Did you mean require?
in /home/p810/dev/phel-lang/vendor/.././/test.phel:1

1| (ns test\test
2|   (:require test\config\mail :as blank)
3|   (:reuire test\config\mail))
```

Would love some feedback if there's a better way to implement/handle this, and would be happy to submit a PR for this feature if it's something you guys decide to implement in the language!

**Comment by mabasic** [comment]
This seems like the exact thing that would have saved me time when miss typing keywords. Nice work!

**Comment by jenshaase** [comment]
@p810 Thanks for your commit. I added a comment to you change. Feel free to create a PR, I would like to merge it.

**Comment by p810** [comment]
@jenshaase updated :+1: The keyword in question is now also pointed to in the stack trace to make it more visible for the dev.
