### ISSUE TITLE
Improve "You can not use this 'recur here" error message 

### ISSUE THREAD

**Issue by Chemaclass** [phel-lang/phel-lang#491]
Sometimes I find it difficult for me to understand "Why I can't call 'recur here?"... maybe we could improve this error message by providing more context, reasons, and maybe how to fix it? In case yes, we could think to apply to similar messages?

I don't have a better solution right now, but we can think about it 🤔

**Comment by Chemaclass** [comment]
@jenshaase I am thinking about this issue. Maybe this example can help us clarify the current status on this.
```phel
# Example A
(defn factorial [n]
  (if (<= n 1)
    n
    (* n (factorial (dec n)))))

(println (factorial 5)) # 120 ; It worked!
```

However, using `recur` instead of the function name we get the error:
```phel
# Example B
(defn factorial [n]
  (if (<= n 1)
    n
    (* n (recur (dec n)))))

(println (factorial 5)) # ERROR: Can't call 'recur here
```

I got two questions at this point:
- would it make sense to allow the Example B to work as well? How complex technically would that be?
- how complex would it be to add additional context to the error message `Can't call 'recur here` to add more info?

**Comment by jenshaase** [comment]
Recur does some magic when it is compiled. It basically refractors the code to a while loop. This eliminates the need for additional function calls. This optimization is often called tail call optimization.

To correctly use recur you can think of it similar to a return statement in PHP. For example `1 + return 10` will not work there.

I think we should improve the error message and make clear how recur should be used.

**Comment by Chemaclass** [comment]
Maybe we could even consider creating a special blog post to talk about the potential of recur and how to use it effectively with different examples. This could be a first step. Would you @jenshaase or @smeghead would like to give a try? An example of what I mean is https://phel-lang.org/blog/map-filter-reduce/ I think it would be great to start creating such blog posts again

**Comment by smeghead** [comment]
I think it's a great idea to help people understand more about recur through blog posts.

First, I was curious about what kind of error message Clojure outputs in the same situation.

> Syntax error (UnsupportedOperationException) compiling recur at (Main.clj:4:10). Can only recur from tail position

I felt that the presence of the word "tail position" might be an opportunity for users who saw this error message to investigate the concept of tail recursion, so it was not a bad message.


Next, I researched the Clojure spec to my own better understand `recur` spec.

* `fn` and `loop` set recursion points.
* `recur` rebinds the argument to the previous recursion point. (Image of calling a recursive function)
* "The expression recur must exactly match the arity of the recursion point."

Maybe the code below resulted in an error because of the last condition. Moreover, the error messages were difficult to understand.

````clojure
(defn fact [n & [acc]]
   (if (<= n 0)
       acc
       (recur (dec n) (* (or acc 1) n))))
(println (fact 5))

Syntax error (UnsupportedOperationException) compiling at (Main.clj:8:1). nth not supported on this type: Long
````

I'm guessing that if a variable length argument is defined using &, the condition "expression recur must exactly match the arity of the recursion point" is not met. .

This is my opinion, but I think it's better to avoid making recursive calls with recur to recursion points defined by `defn` and `fn` if possible.
These are just my personal opinions regarding the clojure `recur` specifications.

**Comment by Chemaclass** [comment]
New blog post created by @smeghead https://phel-lang.org/blog/loop-and-recur/
Link to blog post added to phel exeption https://github.com/phel-lang/phel-lang/commit/813aafa8d862c5b7d84b825deb73bf1fa7ac8f18
