### ISSUE TITLE
Improve error messages in the REPL

### ISSUE THREAD

**Issue by danirod** [phel-lang/phel-lang#602]
Currently, if some code fails when being evaluated in a REPL session, it prints a very long stack trace that makes difficult to grasp the reason on why the code failed. It might be useful if the actual error reason was more prominent or at least the stack traces were hidden by default.

![Screenshot 2023-05-30 at 20 09 46](https://github.com/phel-lang/phel-lang/assets/1568690/0d6e135b-8750-4174-b99c-746ff91dd694)

**Comment by Chemaclass** [comment]
First of all, thanks for reporting this idea, @danirod! 💡 Actually, that's not an "exception" but a "PHP Notice", which is tricky, because I think it should be an exception... but that's another topic. 

You're right, there is a lot of noise that doesn't provide value while trying to understand why it occurred that "error" in your phel code. I created a [PR](https://github.com/phel-lang/phel-lang/pull/604) minimising the noise that you get on PHP Notices, and also the Exception messages as well, moving the stack-trace to another file to keep a timestamp of each error that could be useful later for debugging purposes. Let me know if this helps you, or if you have any feedback to make it even better/useful.

**Comment by Chemaclass** [comment]
Deprecations and Notices errors were improved. The output message is narrowed to the important information, reducing the noice from PHP. Additionally, it will be renderer in a error.log file, so you can keep track of those errors to catch them at a later point if needed.

Let me know if you experience any error with this, or if you see other opportunities to improve the developer experience. Thanks!
