### ISSUE TITLE
Incorrect location of vendor directory when run from `bin` entry point in a phel project installed with `composer require`.

### ISSUE THREAD

**Issue by smeghead** [phel-lang/phel-lang#739]
| Q                   | A               |
|---------------------|-----------------|
| Phel version        | 0.15           |
| PHP version         | 8.2.21           |

#### Summary

When you `composer require` a command line project written in phel-lang that provides commands, there may be an error in recognizing the vendor directory.

#### Current behavior

https://github.com/smeghead/phel-saraudon
This repository contains a file in bin/saraudon that serves as the runtime entry point, specified by a `composer.json` with a `bin` entry.

```bash
$ composer require --dev smeghead/phel-saraudon
$ vendor/bin/saraudon
```

At this time, I checked `$this->vendorDirectory` in `src/php/Command/Infrastructure/ComposerVendorDirectoriesFinder.php` and found the following value.

```
string(65) "/tmp/saraudon-example/vendor/smeghead/phel-saraudon/bin/../vendor"
```

#### How to reproduce

```bash
$ composer require --dev smeghead/phel-saraudon
$ vendor/bin/saraudon
```
check `$this->vendorDirectory` in `src/php/Command/Infrastructure/ComposerVendorDirectoriesFinder.php` 

#### Expected behavior

Isn't `/tmp/saraudon-example/vendor/` correct?

This seemed to cause the vendor directory lookup to fail.

**Comment by Chemaclass** [comment]
Interesting catch. You're right! Feel free to work on it these days if you want, otherwise I will work on this next week, thanks for reporting it.

**Comment by smeghead** [comment]
@Chemaclass 
I have done additional research and it seems that `Gacela` is also involved.
I would appreciate it if you could fix it for me, as it seems to be a very broad issue that unfortunately cannot be handled in a few days.

**Comment by Chemaclass** [comment]
@smeghead, after some investigation, these are some learnings to share:

Checking `$this->vendorDirectory` we can see that this is formed with the values from `appRootDir` and `VendorDir`
![Screenshot 2024-07-28 at 22 03 29](https://github.com/user-attachments/assets/cabc951a-6e6e-4092-b8d0-27665c9d4045)

Gacela allows you to define the entry point of your app at the time of [bootstrapping](https://gacela-project.com/docs/bootstrap/#initializing-gacela) it, which in Phel happens on the `Phel::run($rootDir)`. As you can see, this is something you use in your `bin/saraudon` entrypoint:

![Screenshot 2024-07-28 at 21 55 17](https://github.com/user-attachments/assets/88467e22-04cc-464b-89ef-017ffb514076)

![Screenshot 2024-07-28 at 21 54 21](https://github.com/user-attachments/assets/8901e015-326a-4997-b238-16248d2683fe)


TIPS:
1. In your `bin/saraudon` try using `getcwd()` instead of `__DIR__`
  a. `getcwd()` gives you the relative path from where you are using the script
  b. `__DIR__` gives you the absolute path of the file itself
2. Check out the [bin/phel entrypoint](https://github.com/phel-lang/phel-lang/blob/main/bin/phel#L42), and how it defines the appRootDir variable

PS: the vendor value can be changed from [phel config itself](https://phel-lang.org/documentation/configuration/#vendordir)

How does this helps you so far, @smeghead ? I am not sure if there is any changes neccessary on phel or gacela at this point related to this. Let me know.

**Comment by smeghead** [comment]
Thank you for investigating.

I understand that the problem is not with phel or gacela, but with the way the project root directory is specified in the first argument of Phel::run.

Considering that it is installed under the `vendor` directory with `composer require` and may be run from the `bin` directory, we have modified it to identify the project root directory in the same way that it looks for autoload.php.

https://github.com/smeghead/phel-saraudon/blob/7724a3e464ce946626e0c067797a4c5d54081685/bin/saraudon#L9-L23

This fix ensures that the `composer require` will execute correctly and recognize the `vendor` directory, even if it is installed under the `vendor` directory and executed from the `bin` directory.

Thank you for your time.
